# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jipUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setHorizontalSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_model = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_model.setEditable(True)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.comboBox_model.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_model, 0, 1, 1, 1)
        self.lineEdit_pcb = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pcb.setObjectName("lineEdit_pcb")
        self.gridLayout_2.addWidget(self.lineEdit_pcb, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 6, 1, 1)
        self.lineEdit_workerid = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_workerid.setObjectName("lineEdit_workerid")
        self.gridLayout_2.addWidget(self.lineEdit_workerid, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_storeid = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_storeid.setObjectName("lineEdit_storeid")
        self.gridLayout_2.addWidget(self.lineEdit_storeid, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.lineEdit_machineid = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_machineid.setObjectName("lineEdit_machineid")
        self.gridLayout_2.addWidget(self.lineEdit_machineid, 1, 5, 1, 1)
        self.comboBox_result = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_result.setEditable(True)
        self.comboBox_result.setObjectName("comboBox_result")
        self.comboBox_result.addItem("")
        self.comboBox_result.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_result, 1, 9, 1, 1)
        self.comboBox_board = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_board.setEditable(True)
        self.comboBox_board.setObjectName("comboBox_board")
        self.comboBox_board.addItem("")
        self.comboBox_board.addItem("")
        self.comboBox_board.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_board, 1, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 8, 1, 1)
        self.lineEdit_version = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.gridLayout_2.addWidget(self.lineEdit_version, 0, 7, 1, 1)
        self.comboBox_gw = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_gw.setEditable(True)
        self.comboBox_gw.setDuplicatesEnabled(False)
        self.comboBox_gw.setFrame(True)
        self.comboBox_gw.setObjectName("comboBox_gw")
        self.comboBox_gw.addItem("")
        self.comboBox_gw.addItem("")
        self.comboBox_gw.addItem("")
        self.comboBox_gw.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_gw, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 6, 1, 1)
        self.lineEdit_serino = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_serino.setObjectName("lineEdit_serino")
        self.gridLayout_2.addWidget(self.lineEdit_serino, 0, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_zj = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_zj.setObjectName("lineEdit_zj")
        self.gridLayout_2.addWidget(self.lineEdit_zj, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lineEdit_gw_thickness = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_gw_thickness.setObjectName("lineEdit_gw_thickness")
        self.horizontalLayout.addWidget(self.lineEdit_gw_thickness)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 3)
        self.verticalLayout_4.setStretch(2, 6)
        self.verticalLayout_4.setStretch(3, 2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.label_15 = QtWidgets.QLabel(self.tab_1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_15.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_result_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_result_2.setEditable(True)
        self.comboBox_result_2.setObjectName("comboBox_result_2")
        self.comboBox_result_2.addItem("")
        self.comboBox_result_2.addItem("")
        self.comboBox_result_2.addItem("")
        self.comboBox_result_2.addItem("")
        self.comboBox_result_2.addItem("")
        self.comboBox_result_2.addItem("")
        self.comboBox_result_2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_result_2, 1, 7, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 1, 6, 1, 1)
        self.comboBox_gw_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gw_2.setEnabled(False)
        self.comboBox_gw_2.setEditable(False)
        self.comboBox_gw_2.setObjectName("comboBox_gw_2")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.comboBox_gw_2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_gw_2, 0, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.comboBox_model_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_model_2.setEditable(True)
        self.comboBox_model_2.setObjectName("comboBox_model_2")
        self.comboBox_model_2.addItem("")
        self.comboBox_model_2.addItem("")
        self.comboBox_model_2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_model_2, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 2, 1, 1)
        self.lineEdit_workerid_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_workerid_2.setObjectName("lineEdit_workerid_2")
        self.gridLayout_5.addWidget(self.lineEdit_workerid_2, 1, 1, 1, 1)
        self.lineEdit_serino_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_serino_2.setObjectName("lineEdit_serino_2")
        self.gridLayout_5.addWidget(self.lineEdit_serino_2, 0, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 0, 7, 1, 1)
        self.comboBox_line = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_line.setEditable(True)
        self.comboBox_line.setObjectName("comboBox_line")
        self.comboBox_line.addItem("")
        self.comboBox_line.addItem("")
        self.comboBox_line.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_line, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 2, 1, 1)
        self.lineEdit_machineid_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_machineid_2.setObjectName("lineEdit_machineid_2")
        self.gridLayout_5.addWidget(self.lineEdit_machineid_2, 1, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_use_age = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_use_age.setText("")
        self.lineEdit_use_age.setObjectName("lineEdit_use_age")
        self.gridLayout_5.addWidget(self.lineEdit_use_age, 2, 1, 1, 1)
        self.gridLayout_5.setColumnMinimumWidth(0, 1)
        self.gridLayout_5.setColumnMinimumWidth(1, 3)
        self.gridLayout_5.setColumnMinimumWidth(2, 1)
        self.gridLayout_5.setColumnMinimumWidth(3, 3)
        self.gridLayout_5.setColumnMinimumWidth(4, 1)
        self.gridLayout_5.setColumnMinimumWidth(5, 3)
        self.gridLayout_5.setColumnMinimumWidth(6, 1)
        self.gridLayout_5.setColumnMinimumWidth(7, 3)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 3)
        self.gridLayout_5.setColumnStretch(4, 1)
        self.gridLayout_5.setColumnStretch(5, 3)
        self.gridLayout_5.setColumnStretch(6, 1)
        self.gridLayout_5.setColumnStretch(7, 3)
        self.verticalLayout_6.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_8.addWidget(self.tableWidget_2)
        self.verticalLayout_7.addWidget(self.groupBox_9)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_10)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_2.addWidget(self.label_29)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_10)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_6.addWidget(self.groupBox_10)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.verticalLayout_6.setStretch(2, 6)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_20.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_9.addWidget(self.label_20)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.lineEdit_serino_3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_serino_3.setObjectName("lineEdit_serino_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_serino_3)
        self.label_26 = QtWidgets.QLabel(self.groupBox_11)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.lineEdit_line = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_line.setObjectName("lineEdit_line")
        self.horizontalLayout_3.addWidget(self.lineEdit_line)
        self.verticalLayout_10.addWidget(self.groupBox_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(20)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        self.verticalLayout_10.addWidget(self.tableWidget_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_31 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_6.setHorizontalSpacing(9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_32 = QtWidgets.QLabel(self.groupBox_13)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 0, 0, 1, 1)
        self.comboBox_model_3 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_model_3.setEditable(True)
        self.comboBox_model_3.setObjectName("comboBox_model_3")
        self.comboBox_model_3.addItem("")
        self.comboBox_model_3.addItem("")
        self.comboBox_model_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_model_3, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_13)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_13)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 1, 0, 1, 1)
        self.lineEdit_machineid_3 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_machineid_3.setObjectName("lineEdit_machineid_3")
        self.gridLayout_6.addWidget(self.lineEdit_machineid_3, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_13)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 1, 2, 1, 1)
        self.comboBox_board_2 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_board_2.setEditable(True)
        self.comboBox_board_2.setObjectName("comboBox_board_2")
        self.comboBox_board_2.addItem("")
        self.comboBox_board_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_board_2, 1, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_13)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 1, 4, 1, 1)
        self.comboBox_result_3 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_result_3.setEditable(True)
        self.comboBox_result_3.setObjectName("comboBox_result_3")
        self.comboBox_result_3.addItem("")
        self.comboBox_result_3.addItem("")
        self.comboBox_result_3.addItem("")
        self.comboBox_result_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_result_3, 1, 5, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_13)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 2, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_2, 2, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_13)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 2, 4, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: rgb(0, 0, 230);")
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 2, 5, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_13)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 0, 2, 1, 1)
        self.lineEdit_serino_4 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_serino_4.setObjectName("lineEdit_serino_4")
        self.gridLayout_6.addWidget(self.lineEdit_serino_4, 0, 3, 1, 1)
        self.lineEdit_pcb_2 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_pcb_2.setObjectName("lineEdit_pcb_2")
        self.gridLayout_6.addWidget(self.lineEdit_pcb_2, 0, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_13)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 4, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_15)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(6)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        self.verticalLayout_14.addWidget(self.tableWidget_4)
        self.verticalLayout_13.addWidget(self.groupBox_15)
        self.verticalLayout_12.addWidget(self.groupBox_14)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_43 = QtWidgets.QLabel(self.groupBox_16)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_5.addWidget(self.label_43)
        self.comboBox_auditor = QtWidgets.QComboBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_auditor.setFont(font)
        self.comboBox_auditor.setEditable(True)
        self.comboBox_auditor.setObjectName("comboBox_auditor")
        self.comboBox_auditor.addItem("")
        self.comboBox_auditor.addItem("")
        self.comboBox_auditor.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_auditor)
        self.label_44 = QtWidgets.QLabel(self.groupBox_16)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_5.addWidget(self.label_44)
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_16)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_5.addWidget(self.textEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_12.addWidget(self.groupBox_16)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 3)
        self.verticalLayout_12.setStretch(2, 6)
        self.verticalLayout_12.setStretch(3, 2)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.label_40 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_15.addWidget(self.label_40)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_model, self.lineEdit_pcb)
        MainWindow.setTabOrder(self.lineEdit_pcb, self.comboBox_gw)
        MainWindow.setTabOrder(self.comboBox_gw, self.lineEdit_version)
        MainWindow.setTabOrder(self.lineEdit_version, self.lineEdit_serino)
        MainWindow.setTabOrder(self.lineEdit_serino, self.lineEdit_workerid)
        MainWindow.setTabOrder(self.lineEdit_workerid, self.lineEdit_storeid)
        MainWindow.setTabOrder(self.lineEdit_storeid, self.lineEdit_machineid)
        MainWindow.setTabOrder(self.lineEdit_machineid, self.comboBox_board)
        MainWindow.setTabOrder(self.comboBox_board, self.comboBox_result)
        MainWindow.setTabOrder(self.comboBox_result, self.lineEdit_zj)
        MainWindow.setTabOrder(self.lineEdit_zj, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.lineEdit_gw_thickness)
        MainWindow.setTabOrder(self.lineEdit_gw_thickness, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.comboBox_model_2)
        MainWindow.setTabOrder(self.comboBox_model_2, self.lineEdit_serino_2)
        MainWindow.setTabOrder(self.lineEdit_serino_2, self.comboBox_gw_2)
        MainWindow.setTabOrder(self.comboBox_gw_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.lineEdit_workerid_2)
        MainWindow.setTabOrder(self.lineEdit_workerid_2, self.comboBox_line)
        MainWindow.setTabOrder(self.comboBox_line, self.lineEdit_machineid_2)
        MainWindow.setTabOrder(self.lineEdit_machineid_2, self.comboBox_result_2)
        MainWindow.setTabOrder(self.comboBox_result_2, self.lineEdit_use_age)
        MainWindow.setTabOrder(self.lineEdit_use_age, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.textEdit_2)
        MainWindow.setTabOrder(self.textEdit_2, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.lineEdit_serino_3)
        MainWindow.setTabOrder(self.lineEdit_serino_3, self.lineEdit_line)
        MainWindow.setTabOrder(self.lineEdit_line, self.tableWidget_3)
        MainWindow.setTabOrder(self.tableWidget_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.comboBox_model_3)
        MainWindow.setTabOrder(self.comboBox_model_3, self.lineEdit_machineid_3)
        MainWindow.setTabOrder(self.lineEdit_machineid_3, self.comboBox_board_2)
        MainWindow.setTabOrder(self.comboBox_board_2, self.comboBox_result_3)
        MainWindow.setTabOrder(self.comboBox_result_3, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.tableWidget_4)
        MainWindow.setTabOrder(self.tableWidget_4, self.comboBox_auditor)
        MainWindow.setTabOrder(self.comboBox_auditor, self.textEdit_3)
        MainWindow.setTabOrder(self.textEdit_3, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">新治具验收</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "验收基础信息"))
        self.label_2.setText(_translate("MainWindow", "种类："))
        self.comboBox_model.setItemText(0, _translate("MainWindow", "刮刀"))
        self.comboBox_model.setItemText(1, _translate("MainWindow", "钢网"))
        self.comboBox_model.setItemText(2, _translate("MainWindow", "印刷治具"))
        self.label_3.setText(_translate("MainWindow", "PCB料号："))
        self.label_10.setText(_translate("MainWindow", "板面："))
        self.label_9.setText(_translate("MainWindow", "机种/型号："))
        self.label_7.setText(_translate("MainWindow", "工号："))
        self.label_8.setText(_translate("MainWindow", "库位编号："))
        self.comboBox_result.setItemText(0, _translate("MainWindow", "PASS"))
        self.comboBox_result.setItemText(1, _translate("MainWindow", "FAIL"))
        self.comboBox_board.setItemText(0, _translate("MainWindow", "BOT"))
        self.comboBox_board.setItemText(1, _translate("MainWindow", "TOP"))
        self.comboBox_board.setItemText(2, _translate("MainWindow", "B/T"))
        self.label_11.setText(_translate("MainWindow", "验收结果："))
        self.comboBox_gw.setItemText(0, _translate("MainWindow", "SUS304"))
        self.comboBox_gw.setItemText(1, _translate("MainWindow", "SUS304+纳米"))
        self.comboBox_gw.setItemText(2, _translate("MainWindow", "FG"))
        self.comboBox_gw.setItemText(3, _translate("MainWindow", "FG+纳米"))
        self.label_4.setText(_translate("MainWindow", "钢网材质："))
        self.label_5.setText(_translate("MainWindow", "版本："))
        self.label_6.setText(_translate("MainWindow", "序列号："))
        self.label_12.setText(_translate("MainWindow", "治具料号："))
        self.groupBox_3.setTitle(_translate("MainWindow", "验收项目详细信息"))
        self.groupBox_4.setTitle(_translate("MainWindow", "检验项目"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "检验项目"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "检验标准"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "检验工具"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "实际值"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "判断结果"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.groupBox_5.setTitle(_translate("MainWindow", "确认验收"))
        self.label_13.setText(_translate("MainWindow", "钢网厚度："))
        self.label_14.setText(_translate("MainWindow", "备注："))
        self.pushButton.setText(_translate("MainWindow", "验收"))
        self.label_15.setText(_translate("MainWindow", "首次验收，请一次录入治具各项基础信息；非首次验收，请直接扫描治具序列号。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "治具验收"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>治具管控操作</p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "使用操作"))
        self.comboBox_result_2.setItemText(0, _translate("MainWindow", "72小时下线"))
        self.comboBox_result_2.setItemText(1, _translate("MainWindow", "8小时下线"))
        self.comboBox_result_2.setItemText(2, _translate("MainWindow", "更换工单"))
        self.comboBox_result_2.setItemText(3, _translate("MainWindow", "刮刀损坏"))
        self.comboBox_result_2.setItemText(4, _translate("MainWindow", "钢网损伤"))
        self.comboBox_result_2.setItemText(5, _translate("MainWindow", "钢网脏污"))
        self.comboBox_result_2.setItemText(6, _translate("MainWindow", "临时停线"))
        self.label_24.setText(_translate("MainWindow", "原因："))
        self.comboBox_gw_2.setItemText(0, _translate("MainWindow", "领用"))
        self.comboBox_gw_2.setItemText(1, _translate("MainWindow", "出库检查"))
        self.comboBox_gw_2.setItemText(2, _translate("MainWindow", "上线"))
        self.comboBox_gw_2.setItemText(3, _translate("MainWindow", "下线"))
        self.comboBox_gw_2.setItemText(4, _translate("MainWindow", "归还检查"))
        self.comboBox_gw_2.setItemText(5, _translate("MainWindow", "清洁"))
        self.comboBox_gw_2.setItemText(6, _translate("MainWindow", "检查"))
        self.comboBox_gw_2.setItemText(7, _translate("MainWindow", "入库"))
        self.label_25.setText(_translate("MainWindow", "操作"))
        self.label_18.setText(_translate("MainWindow", "种类："))
        self.comboBox_model_2.setItemText(0, _translate("MainWindow", "刮刀"))
        self.comboBox_model_2.setItemText(1, _translate("MainWindow", "钢网"))
        self.comboBox_model_2.setItemText(2, _translate("MainWindow", "印刷治具"))
        self.label_19.setText(_translate("MainWindow", "序列号："))
        self.pushButton_3.setText(_translate("MainWindow", "确认"))
        self.comboBox_line.setItemText(0, _translate("MainWindow", "YS_SMT1-1"))
        self.comboBox_line.setItemText(1, _translate("MainWindow", "YS_SMT1-2"))
        self.comboBox_line.setItemText(2, _translate("MainWindow", "YS_SMT3"))
        self.label_21.setText(_translate("MainWindow", "工单："))
        self.label_22.setText(_translate("MainWindow", "员工工号："))
        self.label_23.setText(_translate("MainWindow", "线别："))
        self.label_28.setText(_translate("MainWindow", "使用次数："))
        self.groupBox_8.setTitle(_translate("MainWindow", "其他操作"))
        self.groupBox_9.setTitle(_translate("MainWindow", "检验项目"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "检验项目"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "检验标准"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "检验工具"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "实际值"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "判断结果"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.groupBox_10.setTitle(_translate("MainWindow", "状态变更"))
        self.label_29.setText(_translate("MainWindow", "状态："))
        self.comboBox.setItemText(0, _translate("MainWindow", "可用"))
        self.comboBox.setItemText(1, _translate("MainWindow", "暂停"))
        self.comboBox.setItemText(2, _translate("MainWindow", "报废"))
        self.label_30.setText(_translate("MainWindow", "备注："))
        self.pushButton_2.setText(_translate("MainWindow", "变更"))
        self.label_20.setText(_translate("MainWindow", "请选择治具种类"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "治具管控"))
        self.groupBox_11.setTitle(_translate("MainWindow", "查询"))
        self.label_16.setText(_translate("MainWindow", "序列号"))
        self.label_26.setText(_translate("MainWindow", "线体"))
        self.pushButton_4.setText(_translate("MainWindow", "查询"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序列号"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "线体"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "工单"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "机种/型号"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PCB料号"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "操作时间"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "操作人员"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "钢网厚度"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "厚度备注"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "库位号码"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "下线原因"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "使用备注"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "机种版本"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "板面"))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "用量"))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "种类"))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "审核人"))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "制程段"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "治具状态查询"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p>测温板管理</p></body></html>"))
        self.groupBox_13.setTitle(_translate("MainWindow", "验收基础信息"))
        self.label_32.setText(_translate("MainWindow", "状态："))
        self.comboBox_model_3.setItemText(0, _translate("MainWindow", "新做"))
        self.comboBox_model_3.setItemText(1, _translate("MainWindow", "正在使用"))
        self.comboBox_model_3.setItemText(2, _translate("MainWindow", "报废"))
        self.label_42.setText(_translate("MainWindow", "板厚："))
        self.label_35.setText(_translate("MainWindow", "机种名称："))
        self.label_34.setText(_translate("MainWindow", "制程段："))
        self.comboBox_board_2.setItemText(0, _translate("MainWindow", "SMT"))
        self.comboBox_board_2.setItemText(1, _translate("MainWindow", "DIP"))
        self.label_38.setText(_translate("MainWindow", "制作人："))
        self.comboBox_result_3.setItemText(0, _translate("MainWindow", "王松"))
        self.comboBox_result_3.setItemText(1, _translate("MainWindow", "赵东杰"))
        self.comboBox_result_3.setItemText(2, _translate("MainWindow", "彭豪豪"))
        self.comboBox_result_3.setItemText(3, _translate("MainWindow", "王广德"))
        self.label_36.setText(_translate("MainWindow", "线别："))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "HW_BOSA1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "HW_BOSA2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "HW_BOSA3"))
        self.label_37.setText(_translate("MainWindow", "使用次数："))
        self.label_39.setText(_translate("MainWindow", "0"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1.0"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "1.6"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "2.0"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "3.0"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "3.3"))
        self.label_41.setText(_translate("MainWindow", "编号："))
        self.label_33.setText(_translate("MainWindow", "PCB料号："))
        self.groupBox_14.setTitle(_translate("MainWindow", "验收项目详细信息"))
        self.groupBox_15.setTitle(_translate("MainWindow", "检验项目"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "检验项目"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "检验标准"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "检验工具"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "实际值"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "判断结果"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.groupBox_16.setTitle(_translate("MainWindow", "确认验收"))
        self.label_43.setText(_translate("MainWindow", "审核人："))
        self.comboBox_auditor.setItemText(0, _translate("MainWindow", "李令保"))
        self.comboBox_auditor.setItemText(1, _translate("MainWindow", "唐亚飞"))
        self.comboBox_auditor.setItemText(2, _translate("MainWindow", "杨洋"))
        self.label_44.setText(_translate("MainWindow", "备注："))
        self.pushButton_5.setText(_translate("MainWindow", "录入"))
        self.label_40.setText(_translate("MainWindow", "请扫描测温板编号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "测温板管理"))
        self.menu.setTitle(_translate("MainWindow", "人员管理"))

